n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro: '))
# ANTIGO print('A soma entre', n1, 'e', n2, 'vale: {}'.format(n1+n2))
print('A some entre {} e {} vale: {}'.format(n1, n2, n1 + n2))
print('A soma entre {0} e {1} vale: {2}'.format(n1, n2, n1 + n2))
