print('----------- Desafio 004 -----------')
print('Analisador')
user_input = input('Digite algo: ')
print('Oque você digitou é um(a): {}'.format(type(user_input)))
print('Só tem espaços? {}'.format(user_input.isspace()))
print('É um número? {}'.format(user_input.isnumeric()))
print('Pertence a tabela ASCII? {}'.format(user_input.isascii()))
print('Tem somente letras? {}'.format(user_input.isalpha()))
print('É alfanumerico? {}'.format(user_input.isnumeric()))
print('Tem apenas letras minusculas? {}'.format(user_input.islower()))
print('Tem apenas letras maiusculas? {}'.format(user_input.isupper()))
print('Esta capitalizada? {}'.format(user_input.istitle()))
